[package]
name = "decert_scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
confparse = {path = "../confparse"}
serde = {version = "1.0.214", features = ["derive", "rc"]}
serde_json = "1.0.132"
